datasources:
    list1:
        name: List 1
        regex: /list.*1$$/i
        columns: 
            - name: Child Unique ID
              unique: true
            - name: Gender
            - name: Ethnicity
            - name: Date of Birth
              type: date
            - name: Age of Child (Years)
              regex: /age of child.*/i
            - name: Date of Contact
              type: date
              unique: true
            - name: Contact Source
              unique: true

    list2:
        name: List 2
        regex: /list.*2/i
        columns:
            - name: Child Unique ID
              unique: true
            - name: Gender
            - name: Ethnicity
            - name: Date of Birth
              type: date
            - name: Age of Child (Years)
              regex: /age of child.*/i
            - name: Assessment start date
              type: date
              unique: true
            - name: Assessment completion date
              type: date
            - name: Organisation completing assessment    

    list3:
        name: List 3
        regex: /list.*3/i
        columns:
            - name: Child Unique ID
              unique: true
            - name: Gender
            - name: Ethnicity
            - name: Date of Birth
              type: date
            - name: Age of Child (Years)
              regex: /age of child.*/i
            - name: Date of referral
              regex: /date of.*referral.*/i
              type: date
              unique: true
            - name: Referral Source
            - name: Referral NFA?
            - name: Number of Referrals in Last 12 Months
            - name: Allocated Team
            - name: Allocated Worker    
    
    list4:
        name: List 4
        regex: /list.*4/i
        columns:
            - name: Child Unique ID
              unique: true
            - name: Gender
            - name: Ethnicity
            - name: Date of Birth
              type: date
            - name: Age of Child (Years)
              regex: /age of child.*/i
            - name: Does the Child have a Disability
            - name: Continuous Assessment Start Date
              type: date
              unique: true
            - name: Child Seen During Continuous Assessment
            - name: Continuous Assessment Date of Authorisation
              type: date
            - name: "Was the child assessed as requiring LA children's social care support"
            - name: Allocated Team
            - name: Allocated Worker

    list5:
        name: List 5
        regex: /list.*5/i
        columns:
            - name: Child Unique ID
              unique: true
            - name: Gender
            - name: Ethnicity
            - name: Date of Birth
              type: date
            - name: Age of Child (Years)
              regex: /age of child.*/i
            - name: Does the Child have a Disability
            - name: Strategy discussion initiating Section 47 Enquiry Start Date
            - name: Was an Initial Child Protection Conference deemed unnecessary?
            - name: Date of Initial Child Protection Conference
              type: date
              unique: true
            - name: Did the Initial Child Protection Conference Result in a Child Protection Plan
            - name: Number of Section 47 Enquiries in the last 12 months
            - name: Number of ICPCs in the last 12 months
            - name: Allocated Team
            - name: Allocated Worker

    list6:
        name: List 6
        regex: /list.*6/i
        columns:
            - name: Child Unique ID
              unique: true
            - name: Gender
            - name: Ethnicity
            - name: Date of Birth
              type: date
            - name: Age of Child (Years)
              regex: /age of child.*/i
            - name: Does the Child have a Disability
            - name: CIN Start Date
              type: date
              unique: true
            - name: Primary Need Code
            - name: Date Child Was Last Seen
              type: date
            - name: CIN Closure Date
              type: date
            - name: Reason for Closure
            - name: Case status
            - name: Allocated Team
            - name: Allocated Worker

    list7:
      name: List 7
      regex: /list.*7/i
      columns:
            - name: Child Unique ID
              unique: true
            - name: Gender
            - name: Ethnicity
            - name: Date of Birth
              type: date
            - name: Age of Child (Years)
              regex: /age of child.*/i
            - name: Does the Child have a Disability
            - name: Child Protection Plan Start Date
              type: date
            - name: Initial Category of Abuse
            - name: Latest Category of Abuse
            - name: Date of the Last Statutory Visit
              type: date
            - name: Was the Child Seen Alone?
            - name: Date of latest review conference
              type: date
            - name: Child Protection Plan End Date
              type: date
            - name: Subject to Emergency Protection Order or Protected Under Police Powers in Last Six Months (Y/N)
              regex: /Subject to Emergency Protection Order.*/i
            - name: Number of Previous Child Protection Plans
            - name: Allocated Team
            - name: Allocated Worker

    list8:
        name: List 8
        regex: /list.*8/i
        columns:
            - name: Child Unique ID
              unique: true
            - name: Gender
            - name: Ethnicity
            - name: Date of Birth
              type: date
            - name: Age of Child (Years)
              regex: /age of child.*/i
            - name: Unaccompanied Asylum Seeking Child (UASC) within the Last 12 Months (Y/N)
              regex: /Unaccompanied Asylum Seeking Child.*/i
            - name: Does the Child have a Disability
            - name: Date Started to be Looked After
              type: date
            - name: "Child's Category of Need"
            - name: Is this a second or subsequent period of being a Looked After Child within the last 12 months (Y/N)
              regex: /.*second or subsequent .* of being a Looked After Child.*/i
            - name: Start date of current legal status
              type: date
            - name: "Child's Legal Status"
            - name: Date of Latest Statutory Review
              type: date
            - name: Date of Last Social Work Visit
              type: date
            - name: What is the permanence plan for this child?
            - name: Date of Last IRO Visit / Contact to the Child
              type: date
            - name: Date of Last Health Assessment
              type: date
            - name: Date of Last Dental Check
              type: date
            - name: Number of Placements in the Last 12 months
            - name: Date Ceased to be Looked After 
              type: date
            - name: Reason Ceased to be Looked After
            - name: Start Date of Most Recent Placement
              type: date
            - name: Placement Type
            - name: Placement Provider
            - name: Placement postcode
            - name: URN of Placement
            - name: Placement Location
            - name: LA of Placement
            - name: "Number of Episodes the Child has been 'Missing' from their Placement in the last 12 months"
            - name: "Number of Episodes the Child has been 'Absent' from their Placement in the last 12 months"
            - name: Was the child offered a Return Interview after their last missing episode (Y/N)?
            - name: Did the child accept a Return Interview after their last missing episode (Y/N)?
            - name: Allocated Team
            - name: Allocated Worker

    list9:
        name: List 9
        regex: /list.*9/i
        columns:
            - name: Child Unique ID
              unique: true
            - name: Gender
            - name: Ethnicity
            - name: Date of Birth
              type: date
            - name: Age of Child (Years)
              regex: /age of child.*/i
            - name: Does the Child have a Disability
            - name: Allocated Team
            - name: Allocated Worker
            - name: Eligibility Category
            - name: LA In Touch 
            - name: Type of Accommodation
            - name: Suitability of Accommodation
            - name: Activity Status

    list10:
        name: List 10
        regex: /list.*10/i
        columns:
            - name: Child Unique ID
              unique: true
            - name: Family identifier
            - name: Gender
            - name: Ethnicity
            - name: Date of Birth
              type: date
            - name: Age of Child (Years)
              regex: /age of child.*/i
            - name: Does the Child have a Disability
            - name: Date the Child Entered Care
              type: date
            - name: Date of Decision that Child Should be Placed for Adoption
              type: date
            - name: Date of Placement Order
              type: date
            - name: Date of Matching Child and Prospective Adopters
              type: date
            - name: Date Placed for Adoption
              type: date
            - name: Date of Adoption Order 
              type: date
            - name: Date of Decision that Child Should No Longer be Placed for Adoption
              type: date
            - name: Reason Why Child No Longer Placed for Adoption
            - name: Date the child was placed for fostering in FFA or concurrent planning placement
              type: date

    list11:
        name: List 11
        regex: /list.*11/i
        columns:
            - name: Individual adopter identifier
              unique: true
            - name: Family identifier
            - name: Gender
            - name: Ethnicity
            - name: Disability
            - name: Is the (prospective) adopter fostering for adoption?
            - name: Date enquiry received
              type: date
            - name: Date Stage 1 started
              type: date
            - name: Date Stage 1 ended
              type: date
            - name: Date Stage 2 started
              type: date
            - name: Date Stage 2 ended
              type: date
            - name: Date application submitted
              type: date
            - name: Date application approved
              type: date
            - name: Date adopter matched with child(ren)
              type: date
            - name: Date child/children placed with adopter(s)
              type: date
            - name: No. of children placed
            - name: Date of Adoption Order
              type: date
            - name: Date of leaving adoption process
              type: date
            - name: Reason for leaving adoption process